package com.example.domain;

import java.util.Date;

public class Todo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.id
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.title
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.start_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.end_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.due_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private Date dueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.created_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.updated_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todos.content
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.id
     *
     * @return the value of todos.id
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.id
     *
     * @param id the value for todos.id
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.title
     *
     * @return the value of todos.title
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.title
     *
     * @param title the value for todos.title
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.start_date
     *
     * @return the value of todos.start_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.start_date
     *
     * @param startDate the value for todos.start_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.end_date
     *
     * @return the value of todos.end_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.end_date
     *
     * @param endDate the value for todos.end_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.due_date
     *
     * @return the value of todos.due_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.due_date
     *
     * @param dueDate the value for todos.due_date
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.created_at
     *
     * @return the value of todos.created_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.created_at
     *
     * @param createdAt the value for todos.created_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.updated_at
     *
     * @return the value of todos.updated_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.updated_at
     *
     * @param updatedAt the value for todos.updated_at
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todos.content
     *
     * @return the value of todos.content
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todos.content
     *
     * @param content the value for todos.content
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}