server:
  port: 8082

spring:
  profiles:
    include: personal
# DB接続共通設定
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=todo
      
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        

