package com.example.mapper;

import com.example.domain.Todos;
import com.example.domain.TodosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TodosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    long countByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int deleteByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int insert(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int insertSelective(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    List<Todos> selectByExampleWithBLOBs(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    List<Todos> selectByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    Todos selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByExampleSelective(@Param("record") Todos record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Todos record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByExample(@Param("record") Todos record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByPrimaryKeySelective(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Todos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 17:49:21 JST 2021
     */
    int updateByPrimaryKey(Todos record);
}