package com.example.mapper;

import com.example.domain.Todo;
import com.example.domain.TodosExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TodosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    long countByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int deleteByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    List<Todo> selectByExampleWithBLOBs(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    List<Todo> selectByExample(TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    Todo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Todo record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todos
     *
     * @mbg.generated Sat Nov 06 19:58:23 JST 2021
     */
    int updateByPrimaryKey(Todo record);
}